version: '3.3'

# Services
services:

  # MySQL Service
  mysql:
    image: mariadb:11
    container_name: messenger-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: messenger
    restart: always
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-data:/var/lib/mysql
      - ./.docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql

  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: messenger-tool
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

  # PHP Service
  php:
    build: ./.docker/php
    container_name: messenger-php
    ports:
      - "80:40990"
      - "40991:40991"
    working_dir: /app
    volumes:
      - ./webman:/app
    environment:
      DB_HOST: mysql
      DB_DATABASE: messenger
      DB_USERNAME: root
      DB_PASSWORD: root
    restart: always
    depends_on:
      - mysql

# Volumes
volumes:

  db-data: