version: '3.8'

# Services
services:

  # Nginx Service


  # MySQL Service
  mysql:
    #image: mariadb:latest
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: messenger
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysqldata:/var/lib/mysql

  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

  # PHP Service
  php:
    build: ./.docker/php
    ports:
      - "80:40990"
      - "40991:40991"
    working_dir: /app
    volumes:
      - ./webman:/app
    environment:
      DB_HOST: mysql
      DB_DATABASE: messenger
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - mysql

# Volumes
volumes:

  mysqldata: